### ISSUE TITLE
Mistype of word in very first question of the very first test

### ISSUE THREAD

**Issue by mnba** [malikpiara/logicola#48]
in Set Q "Meanings and ..." Question 1/10 - mistype in the text of question: the word "_vacuities_" it is written as  vacu**L**ties.

**Comment by malikpiara** [comment]
Dear Minas, It seems I'm unable to replicate the issue on my laptop. Could you tell me which browser and device are you using?

**Comment by mnba** [comment]
I meant the typo in word "vaculties" which is in: 
logicola/contentOld.tsx at line 1097: 
 in `prompt` property 
https://github.com/malikpiara/logicola/blob/47cce3f32a574f23ce3630ef0834b3f2999a1cc2/contentOld.tsx#L1095-L1100 

```
      {
        id: '3.23',
        prompt: 'A net is anything with interstitial vaculties.',  //<<<here
        options: [
          { id: 0, label: 'Too broad' },
          { id: 1, label: 'Too narrow' },
```

This exact issue is not dependent on browser, you probably was replying to another issue, please reply in that too and I will try to find exact code lines for that too. As this one is a pure textual typo, I thought there were no need to specify exact line.

**Comment by malikpiara** [comment]
Yes Minas, you're totally right. I was tired and did not read your initial post correctly. Thank you for flagging this!
